export default {
  "USER1":{
    "username":"0668656378",
    "password":"Angelus27120."
    },
    "USER2":{
    "username":"0683321302",
    "password":"Jackie"
    },
    "USER3":{
    "username":"aksoy.magnoula@hotmail.fr",
    "password":"emnay1505"
    },
    "USER4":{
    "username":"julie.marabgui@gmail.com",
    "password":"marabgui5"
    },
    "USER5":{
    "username":"Soulet_chantal@yahoo.fr",
    "password":"khaina"
    },
    "USER6":{
    "username":"noirot.veronique@gmail.com",
    "password":"Ma24MMa15"
    },
    "USER7":{
    "username":"Flo.gagliardi@live.fr",
    "password":"Fionaflo74!"
    },
    "USER8":{
    "username":"herve.glatigny@wanadoo.fr",
    "password":"nenette60150"
    },
    "USER9":{
    "username":"Franck.dieryck@sfr.fr",
    "password":"17111972"
    },
    "USER10":{
    "username":"a.jacquier541@gmail.com",
    "password":"grognette69"
    },
    "USER11":{
    "username":"0771272036",
    "password":"erami1958"
    },
    "USER12":{
    "username":"jerome.jeantet@bbox.fr",
    "password":"020476"
    },
    "USER13":{
    "username":"0672992864",
    "password":"IsaERM:)"
    },
    "USER14":{
    "username":"0670753138",
    "password":"michel6124"
    },
    "USER15":{
    "username":"titiagnes0@gmail.com",
    "password":"michou21"
    },
    "USER16":{
    "username":"petites-etoiles@hotmail.fr",
    "password":"Papynathan@050149"
    },
    "USER17":{
    "username":"balmemarie@hormail.fr",
    "password":"Abel2016"
    },
    "USER18":{
    "username":"bataillejf@orange.fr",
    "password":"Jetski66"
    },
    "USER19":{
    "username":"Sandrine.vialle1@bbox.fr",
    "password":"081974"
    },
    "USER20":{
    "username":"annelisekieffer@ymail.com",
    "password":"Titiyannalp2017*"
    },
    "USER21":{
    "username":"rafikarahal@gmail.com",
    "password":"Emmanuel13"
    },
    "USER22":{
    "username":"arlete.77@hotmail.fr",
    "password":"goncalves1977"
    },
    "USER23":{
    "username":"Trancolinofabio@gmail.com",
    "password":"trancolino"
    },
    "USER24":{
    "username":"nicolas622a@gmail.com",
    "password":"Goliath62"
    },
    "USER25":{
    "username":"0686567930",
    "password":"110967Ph"
    },
    "USER26":{
    "username":"valenducqpatricia@hotmail.fr",
    "password":"Patougreg"
    },
    "USER27":{
    "username":"danielle.ferrage@outlook.fr",
    "password":"lolita56"
    },
    "USER28":{
    "username":"Stessyrikiki@hotmail.fr",
    "password":"cookyskyline"
    },
    "USER29":{
    "username":"0670455957",
    "password":"1502521t02t2"
    },
    "USER30":{
    "username":"sucema",
    "password":"bite"
    },
    "USER31":{
    "username":"0663390307",
    "password":"Imadzbiblayalibeyrouth2010"
    },
    "USER32":{
    "username":"saizonou.sylvie@orange.fr",
    "password":"7xx4i3s6"
    },
    "USER33":{
    "username":"Christine.klepac@yahoo.fr",
    "password":"087386"
    },
    "USER34":{
    "username":"Corinnerenard@dbmail.com",
    "password":"Etoile\/4"
    },
    "USER35":{
    "username":"ant.demontvalon@gmail.com",
    "password":"b-=TYs5P`8ZPsX`~"
    },
    "USER36":{
    "username":"dosreisabrantesjose@gmail.com",
    "password":"2412"
    },
    "USER37":{
    "username":"agnes.lambert@wanadoo.fr",
    "password":"mazelou0611"
    },
    "USER38":{
    "username":"jean-louis.gibausset@orange.fr",
    "password":"jlGIBAU57"
    },
    "USER39":{
    "username":"David.vicini@sfr.fr",
    "password":"09Rosemarisarah19@"
    },
    "USER40":{
    "username":"francklex@yahoo.fr",
    "password":"lexane2009"
    },
    "USER41":{
    "username":"0699505159",
    "password":"lea15122006"
    },
    "USER42":{
    "username":"0661762287",
    "password":"mnfi2837"
    },
    "USER43":{
    "username":"madison-44@hotmail.fr",
    "password":"hoppens"
    },
    "USER44":{
    "username":"sabrinanet@hotmail.fr",
    "password":"dalila"
    },
    "USER45":{
    "username":"Chevelon",
    "password":"Domdom55#"
    },
    "USER46":{
    "username":"easywriting.fr.gb.de@gmail.com",
    "password":"ambre2017"
    },
    "USER47":{
    "username":"carpentier_guillaume@hotmail.com",
    "password":"gca21gca11"
    },
    "USER48":{
    "username":"emilie_manon@live.fr",
    "password":"Arnaudemilie34"
    },
    "USER49":{
    "username":"David.boultareau@wanadoo.fr",
    "password":"Bouchongv01?"
    },
    "USER50":{
    "username":"Pierrot.michou@laposte.net",
    "password":"amour7385"
    },
    "USER51":{
    "username":"0637240145",
    "password":"88MINUTES"
    },
    "USER52":{
    "username":"0662133661",
    "password":"Damien14!"
    },
    "USER53":{
    "username":"akim.pousse@gmail.com",
    "password":"Pousseaucrime1962"
    },
    "USER54":{
    "username":"0623937012",
    "password":"Normandie17"
    },
    "USER55":{
    "username":"jean-riou55@bbox.fr",
    "password":"lili27400"
    },
    "USER56":{
    "username":"luc59235@gmail.com",
    "password":"Eclipse7373\/\/"
    },
    "USER57":{
    "username":"luc59235@gmail.com",
    "password":"Eclipse7373\/\/"
    }
    
  }